### ISSUE TITLE
Problem with getPossibleMoves method

### ISSUE THREAD

**Issue by Nic7082** [Vuinea/ChessBattle#1]
First of all, your changes are all so clever. I didn't even know how to use enums I will have to learn. Creating a tile class is also an amazing change. The only problem I have seen is with the knight getPossibleMoves method. The current code only gets the forward knight moves, but a knight can also move backwards no matter what color it is.

**Comment by vinodhgnanakkan** [comment]
Thanks for reminding me I was being quite dumb I'll fix that

**Comment by vinodhgnanakkan** [comment]
Ok I fixed it
